### PR TITLE
fix(html): attributes are double escaped

### LINKED ISSUE #84: unexpected escaping of attribute values
having a single attribute like:

```
date = '2019-04-02T08:44:26.000Z';
```
with:
```
<time datetime="${date }">${date}</time>
```

escapes the attribute value like:
```
<time datetime="2019-04-02T08&#x3a;44&#x3a;26.000Z">2019-04-02T08:44:26.000Z</time>
```

even with `context=unsafe`.

similar with:

```
<time data-sly-attribute.datetime="${date @ context = 'unsafe' }">${date}</time>
```

### PR DESCRIPTION
**Pull request by tripodsan**
fixes #84 

the general problem was, that attribute value escaping was done before passing it into the dom handlers, i.e. the jsdom would already receive an escaped attribute value instead of the raw value. this PR moves the responsibility to escape the value to the dom handlers.

changes:
- unescape attribute value when parsed
- remove escaping of attribute values by command stream
- add explicit escaping of attribute values to HtmlDomFactory (during runtime)

### CODE REVIEW

File: src/parser/commands/FunctionBlock.js [hunk 1]
```diff
@@ -27,7 +27,7 @@ class Start extends Command {
     return this._options;
   }
 
-  get arguments() {
+  get args() {
```
Comment (dominique-pfister) [inline src/parser/commands/FunctionBlock.js]: What was wrong with `arguments`? Not consistent or plainly wrong?

Comment (tripodsan) [reply src/parser/commands/FunctionBlock.js]: lint complained about argument being a keyword elswhere....
