### PR TITLE
fix(xss): Allow src/href attributes on images and links

### LINKED ISSUE #66: XSS escaping completely removes src/href attributes on images and links
With #53 the XSS escaping introduced ends up being a bit too zealous and removes all:
- `src` attributes on `images`
- `href` attributes on `links`

### PR DESCRIPTION
**Pull request by ramboz**
Relax the XSS sanitization to allow `src` attributes on images and `href` attributes on links

fix #66

### CODE REVIEW

File: test/runtime_test.js [hunk 1]
```diff
@@ -61,7 +62,7 @@ const GLOBALS = {
     imgTag2: '<img src="fake.jpg" onerror="alert(0)"/>',
     imgTag3: '<img src=`javascript:alert(0)`/>', // grave accent quotes
     imgTag4: '<img src="java	script:alert(0)"/>', // embedded tab
-    imgTag5: '<img src="java#x0A;script:alert(0)"/>', // embedded encoded tab
+    imgTag5: '<img src="java&#x0A;script:alert(0)"/>', // embedded encoded tab
```
Comment (ramboz) [inline test/runtime_test.js]: Fixing a typo so the `src` is an actual XSS attack

File: test/templates/xss.html [hunk 2]
```diff
@@ -18,14 +18,15 @@
 <body>
   <ul>
     <li><a>XSS Link</a></li>
+    <li><a href="http://www.valid.url">Non XSS Link</a></li>
```
Comment (ramboz) [inline test/templates/xss.html]: Allow `href` on links

File: test/templates/xss.html [hunk 3]
```diff
@@ -18,14 +18,15 @@
...
     <li><a name="Foo">XSS Link</a></li>
     <li><a>XSS Link</a></li>
     <li><a>XSS Link</a></li>
     <li><a>XSS Link</a></li>
     <li><a href="#" onclick="alert&#x28;0&#x29;">XSS Link</a></li>
     <li><img></li>
     <li><img src="javascript:alert(0)"/></li>
-    <li><img></li>
+    <li><img src="fake.jpg"></li>
```
Comment (ramboz) [inline test/templates/xss.html]: Allow `src` on images

File: src/runtime/xss_api.js [hunk 4]
```diff
@@ -142,6 +142,41 @@ function sanitizeURL(url) {
...
+
+/**
+ * A sanitization policy that validates src/href attributes against the URI scheme.
+ *
+ * @param {string} tagName The name of the tag currently parsed
+ * @param {string[]} attribs An array of attribute names and values
+ * @returns {object} the resulting sanitized attributes
+ */
+function sanitizeURLPolicy(tagName, attribs) {
+  const initial = [].concat(attribs);
```
Comment (ramboz) [inline src/runtime/xss_api.js]: calling `makeTagPolicy` below actually modifies the input array and removes offending attributes, so we need to create an initial copy to save the links to be escaped below
